swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '2.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v2
schemes:
  - http
  - https
paths:
  /user/transactions?page=1&limit=5:
    get:
      security:
        - Bearer: [ ]
      tags:
        - Transaction Module
      summary: Transactions List
      description: API to get the user's transactions
      parameters:
        - in: header
          description: Join the JWT Bearer token
          name: Authorization
          type: string
          required: true
        - in: path
          description: Page number
          name: page
          type: integer
          required: true
        - in: path
          description: transaction limit per page
          name: limit
          type: integer
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: Return the transaction list successfully
          schema:
            $ref: '#/definitions/ListTransactionsResponse'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized Invalid token
        '404':
          description: Transaction Not Found
        '500':
          description: Internal Server Error
  /user/transaction/add:
    post:
      security:
        - Bearer: [ ]
      tags:
        - Transaction Module
      summary: Transaction Add
      description: API to post new transaction
      parameters:
        - in: header
          description: Join the JWT Bearer token
          name: Authorization
          type: string
          required: true
        - in: body
          description: Transaction Payload
          name: body
          required: true
          schema:
            $ref: '#/definitions/Transaction'
      produces:
        - application/json
      responses:
        '201':
          description: Transaction Created Successfully
          schema:
            $ref: '#/definitions/ApiTransactionResponse'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized Invalid token
        '404':
          description: Transaction Not Found
        '500':
          description: Internal Server Error
  /user/transaction/{id}:
    get:
      security:
        - Bearer: [ ]
      tags:
        - Transaction Module
      summary: Transaction Details
      description: API to get transaction details
      parameters:
        - in: header
          description: Join the JWT Bearer token
          name: Authorization
          type: string
          required: true
        - in: path
          description: ID of the current transaction
          name: Id
          type: string
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: Return the transaction successfully
          schema:
            $ref: '#/definitions/ApiTransactionResponse'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized Invalid token
        '404':
          description: Transaction Not Found
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: [ ]
      tags:
        - Transaction Module
      summary: Transaction Edit
      description: Api to edit the current transaction
      parameters:
        - in: header
          description: Join the JWT Bearer token
          name: Authorization
          type: string
          required: true
        - in: body
          description: Update of transaction attributes
          name: body
          required: true
          schema:
            $ref: '#/definitions/Transaction'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction was successfully modified
          schema:
            $ref: '#/definitions/ApiTransactionResponse'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized Invalid token
        '404':
          description: Transaction Not Found
        '500':
          description: Internal Server Error
    delete:
      security:
        - Bearer: [ ]
      tags:
        - Transaction Module
      summary: Transaction Delete
      description: Api to delete the current transaction
      parameters:
        - in: header
          description: Join the JWT Bearer token
          name: Authorization
          type: string
          required: true
        - in: path
          description: delete the current transaction
          name: Id
          type: string
          required: true
      produces:
        - application/json
      responses:
        '201':
          description: Transaction was successfully deleted
          schema:
            $ref: '#/definitions/DeleteTransactionResponse'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized Invalid token
        '404':
          description: Transaction Not Found
        '500':
          description: Internal Server Error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  transaction:
    type: object
    properties:
      token:
        type: string
      status:
        type: integer
        description: status of the request
      message:
        type: string
        description: message of the request
      body:
        type: object
        properties:
          description:
            type: string
          amount:
            type: number
            format: float
          balanceType:
            type: string
          CreatedAt:
            type: string
            format: date
            description: auto increment creation date
  ListTransactionsResponse:
    type: object
    properties:
      status:
        type: integer
        description: status of the request
      message:
        type: string
        description: message of the request
      body:
        type: array
        items:
          type: object
          properties:
            id:
              type: string
            description:
              type: string
            amount:
              type: number
              format: float
            balanceType:
              type: string
            CreatedAt:
              type: string
              format: date
              description: auto increment creation date
  ApiTransactionResponse:
    type: object
    properties:
      token:
        type: string
      status:
        type: integer
        description: status of the request
      message:
        type: string
        description: message of the request
      body:
        type: object
        properties:
          id:
            type: string
          description:
            type: string
          amount:
            type: number
            format: float
          balanceType:
            type: string
          CreatedAt:
            type: string
            format: date
            description: auto increment creation date
  DeleteTransactionResponse:
    type: object
    properties:
      token:
        type: string
      status:
        type: integer
        description: status of the request
      message:
        type: string
        description: message of the request